version: "3.9"

services:
  go-api:
    build: ./go-api
    ports:
      - "8080:8080"
    depends_on:
      - python-ml
    restart: always
    environment:
      - ML_SERVICE_URL=http://python-ml:8000/predict
  python-ml:
    build: ./python-ml
    depends_on:
      - redis
    networks:
      - smart-network
    ports:
      - "8000:8000"
    restart: always

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    restart: always
    networks:
      - smart-network

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdb
    ports:
      - "5432:5432"
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always

networks:
  smart-network:
    driver: bridge
    