name: CI/CD Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.USER }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and Push Go API Image
        uses: docker/build-push-action@v4
        with:
          context: ./go-api
          push: true
          tags: ghcr.io/${{ github.repository }}/go-api:latest

      - name: Build and Push Python ML Image
        uses: docker/build-push-action@v4
        with:
          context: ./python-ml
          push: true
          tags: ghcr.io/${{ github.repository }}/python-ml:latest

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            mkdir -p ~/.ssh
            chmod 700 ~/.ssh
            eval $(ssh-agent -s)
            echo "${{ secrets.SSH_KEY }}" | tr -d '\r' | ssh-add -
            ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOST }} << 'EOF'
              cd /home/github/smart-city-iot-platform
              docker-compose pull
              docker-compose up -d --remove-orphans
            EOF


