name: CI/CD Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.USER }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and Push Go API Image
        uses: docker/build-push-action@v4
        with:
          context: ./go-api
          push: true
          tags: ghcr.io/${{ github.repository }}/go-api:latest

      - name: Build and Push Python ML Image
        uses: docker/build-push-action@v4
        with:
          context: ./python-ml
          push: true
          tags: ghcr.io/${{ github.repository }}/python-ml:latest
      - name: Debug SSH Connection
        run: ssh -vvv -i <(echo "${{ secrets.SSH_KEY }}") ${{ secrets.USER }}@${{ secrets.HOST }}

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" | tr -d '\r' | ssh-add -
          ssh-keyscan -H cforrester.org >> ~/.ssh/known_hosts
      - name: Deploy using SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
        run: |
          ssh -o ConnectTimeout=30 -o StrictHostKeyChecking=no github@cforrester.org << 'EOF'
            cd /home/user/smart-city-iot-platform
            docker-compose pull
            docker-compose up -d --remove-orphans
          EOF



